# Test Sheet
#sheet-id: 1vvhIGMPvVF-DtWoYsEbVBvzk_VtLyKuIw_zyLdsB-JY
# Online catalog
sheet-id: 1z4XIiEPMFPpeRgGpdhshiQpmY7A45KzCyZzQ7Ohe85E
template-dir: /Users/kmurray/git/go/src/github.com/WordOfLifeMN/online/templates/
